In [1]:
import numpy as np

In [53]:
arr = np.array([[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]]])

In [54]:
arr

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [55]:
np.attr

AttributeError: module 'numpy' has no attribute 'attr'

In [56]:
np.size

<function numpy.size(a, axis=None)>

In [57]:
np.dtype

numpy.dtype

In [58]:
arr.size

14

In [59]:
arr.dtypes

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [60]:
arr.dtype

dtype('int64')

In [61]:
arr.shape

(1, 7, 2)

In [62]:
arr1 = np.array([],[])

In [63]:
arr.shape

(1, 7, 2)

In [64]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [65]:
arr2.shape

(2, 4)

In [66]:
x = np.array([[1, 1], [1,1],[1,1],[1,1],[1,1],[1,1],[1,1],[1,1],[1,1],[1,1]])

In [67]:
x.shape

(10, 2)

In [68]:
x = np.array([[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]])

In [69]:
x.shape

(7, 2)

In [70]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [71]:
p = np.arange(0,109000000,4)

In [72]:
p

array([        0,         4,         8, ..., 108999988, 108999992,
       108999996])

In [74]:
p_reshape = x + arr

In [75]:
p_reshape

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])